<a href="https://colab.research.google.com/github/Alexypl/data-science/blob/master/Numpy%20-%20basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basics


In [1]:
import numpy as np
np.__version__

'1.18.2'

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolute_import

In [3]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

1D array

In [4]:
x = np.array([1, 2])
x

array([1, 2])

In [5]:
print(x)

[1 2]


In [6]:
type(x)

numpy.ndarray

In [7]:
x.ndim

1

In [8]:
x.shape

(2,)

In [9]:
x.size

2

In [10]:
x.dtype

dtype('int64')

In [11]:
y = np.array([1.3, 12.3, 46.1])
print(y)

[ 1.3 12.3 46.1]


In [12]:
y.dtype

dtype('float64')

2D array


In [13]:
z = np.array([[12, 3], [12, 7]])
z

array([[12,  3],
       [12,  7]])

In [14]:
z.ndim

2

In [15]:
z.shape

(2, 2)

In [16]:
a = np.array([[12, 31, 41],[15, 90, 78]])
print(a)

[[12 31 41]
 [15 90 78]]


In [17]:
a.shape

(2, 3)

3D array

In [18]:
b = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]],
     
     [[3, 2, 1],
      [4, 3, 2]]]
)
b
print(b)

[[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 2 1]]

 [[3 2 1]
  [4 3 2]]]


In [19]:
b.ndim

3

In [20]:
b[0][0][0]

4

Types of dates

In [21]:
import numpy as np
a = np.array([1.2, 2.7, 3.5])
a.dtype

dtype('float64')

In [22]:
a = np.array([1, 2, 3], dtype = 'float')
print(a)
a.dtype

[1. 2. 3.]


dtype('float64')

In [23]:
a = np.array([1, 2, 3], dtype = 'complex')
print(a)
a.dtype

[1.+0.j 2.+0.j 3.+0.j]


dtype('complex128')

In [24]:
a = np.array([1.0, 2.6, 3.3], dtype = 'int')
print(a)
a.dtype

[1 2 3]


dtype('int64')

In [25]:
a = np.array([True, False])
print(a)
a.dtype

[ True False]


dtype('bool')

In [26]:
b = np.array([24, 120, 230], dtype = np.int8)
b.dtype

dtype('int8')

In [27]:
b = np.array([24, 120, 230], dtype = np.int8)
b.dtype

dtype('int8')

Making arrays



In [0]:
import numpy as np

In [29]:
np.zeros(shape=(4, 10), dtype = 'int')


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [30]:
np.ones(shape=(5,5), dtype = 'int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
np.full(shape = (3,3), fill_value = 4, dtype= 'int' )

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(start=5, stop = 10)

array([5, 6, 7, 8, 9])

In [34]:
np.arange(start=100, stop = 10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [35]:
np.arange(start=0, stop = 1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [36]:
np.linspace(start = 0, stop = 1, num = 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [37]:
c = np.arange(15)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
c.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
c.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
c.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Operations on arrays

In [0]:
d = np.array([1, 2, 4, 5])
e = np.array([-1, 2, 3, -9])

In [42]:
d + e
d - e 

array([ 2,  0,  1, 14])

In [43]:
np.add(d, e)
np.subtract(d, e)

array([ 2,  0,  1, 14])

In [44]:
d * e
d / e

array([-1.        ,  1.        ,  1.33333333, -0.55555556])

In [45]:
np.multiply(d, e)
np.divide(d, e)

array([-1.        ,  1.        ,  1.33333333, -0.55555556])

In [46]:
d + 3

array([4, 5, 7, 8])

In [47]:
2 * d

array([ 2,  4,  8, 10])

In [48]:
tablica = np.array([[1, 3], [-2, 0]])
tablica1 = np.array([[6, 0], [-1, 2]])
print(tablica)
print(tablica1)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [49]:
np.dot(tablica, tablica1)

array([[  3,   6],
       [-12,   0]])

In [50]:
np.dot(tablica1, tablica)

array([[ 6, 18],
       [-5, -3]])

Gererating random numbers

In [0]:
x = np.random.seed(0)
x


In [52]:
np.random.randn()

1.764052345967664

In [53]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [54]:
np.random.randn(10, 5)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275, -1.04855297],
       [-1.42001794, -1.70627019,  1.9507754 , -0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036, -1.61389785, -0.21274028, -0.89546656],
       [ 0.3869025 , -0.51080514, -1.18063218, -0.02818223,  0.42833187],
       [ 0.06651722,  0.3024719 , -0.63432209, -0.36274117, -0.67246045]])

In [55]:
np.random.rand()

0.317983179393976

In [56]:
np.random.rand(10)

array([0.41426299, 0.0641475 , 0.69247212, 0.56660145, 0.26538949,
       0.52324805, 0.09394051, 0.5759465 , 0.9292962 , 0.31856895])

In [57]:
np.random.randint(10) # privides number intiger from range 0 - (x in function)

2

In [58]:
np.random.randint(low=10, high=101) 

61

In [59]:
np.random.randint(low=10, high=101, size = 10) # provide [size] random numbers 

array([90, 42, 64, 10, 48, 29, 56, 52, 66, 70])

In [60]:
np.random.choice([3, 1, 34, 41]) # provide random element from list (works on string too)

3

In [61]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.random.shuffle(data)
data

array([4, 5, 0, 1, 7, 9, 6, 3, 2, 8])

Functions

In [63]:
np.exp(1) #Euler's constant

2.718281828459045

In [64]:
np.sqrt(9)

3.0

In [65]:
np.all([2, 3, 1]) # check if all object is true in list

True

In [66]:
np.any([0, 0, 9]) # chech if any object is true in list

True

In [67]:
x = np.random.rand(5)
x

array([0.75610669, 0.39609828, 0.89603839, 0.63892108, 0.89155444])

In [68]:
np.argmax(x)

2

In [69]:
x[np.argmax(x)]

0.896038387509077

In [70]:
x[np.argmin(x)]

0.3960982754233623

In [71]:
np.argsort(x) # show index of values from the less to the most

array([1, 3, 0, 4, 2])

In [72]:
np.max(x)

0.896038387509077

In [73]:
np.max(x)

0.896038387509077

In [74]:
np.min(x)

0.3960982754233623

In [75]:
np.mean(x)

0.7157437740508941

In [76]:
np.median(x)

0.7561066938650409

In [77]:
import numpy as np
np.std(x)

0.18607507835120637

Indexing and cutting arrays


In [78]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [79]:
a[9:]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [80]:
a[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
a = a.reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [82]:
a[0]

array([0, 1, 2, 3, 4])

In [83]:
a[:,0:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16]])

In [84]:
a[0:5,:4]

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18]])

In [85]:
a[1, 2] = 14
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [86]:
a[1:, :3]

array([[ 5,  6, 14],
       [10, 11, 12],
       [15, 16, 17]])

ERROR! Session/line number was not unique in database. History logging moved to new session 59


Iteration

In [87]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [90]:
for row in a: 
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [91]:
for item in a.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


Change of arrays' size

In [92]:
a.shape

(4, 5)

In [93]:
a.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [94]:
a.ravel() # reverse of shape 

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [95]:
a.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Logic masks

In [100]:
a = np.arange(start = -10 , stop = 10, step = 0.5)
a = a.reshape(10,-1)
a

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [101]:
a > 0 

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [102]:
a[a > 0] 

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [104]:
np.bitwise_and(a > -5, a < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [105]:
a[np.bitwise_and(a > -5, a < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [106]:
np.bitwise_or(a < -5 , a > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])